### ISSUE TITLE
Wall Hack

### ISSUE THREAD

**Issue by kadirburlukkara** [SkidBit/Metin-2-Bot-Rubinum2-Pserver#5]
Hey Bro Hello You Are Really Good Work. Farm Bot Stone Detection Problem Solved But 3 versions of the previous wallhack is not working now, and the previous version is not working. THANKS

**Comment by SkidBit** [comment]
I don't support any of the old versions.
AFAIK the wallhack feature is working fine in the newest version of the bot.
The next time get someone who properly translates whatever you want to say, thanks.

**Comment by kadirburlukkara** [comment]
I'm Turkish and I'm trying to write as far as I know. Sorry, but wall hack doesn't work in the current version or I can't. Are you sure it works?

**Comment by SkidBit** [comment]
If the bot is not running, you need to press F4 to activate wallhack. This should always work.

**Comment by SkidBit** [comment]
If the console is filled with "[i] PlayerEnt is NULL" then it could be a bug.

**Comment by kadirburlukkara** [comment]
yeah the console is filled with the text "[i] PlayerEnt NULL" o stone bot works fine, o WALLHACK is not active even though it says ON

**Comment by SkidBit** [comment]
Restart the game, wait until you are loaded into the game and inject again. Is the problem still the same then?

**Comment by SkidBit** [comment]
Are you even playing on Rubinum 2?

**Comment by kadirburlukkara** [comment]
yes the problem is still the same and i play rubinum yeah

**Comment by SkidBit** [comment]
Okay, I need some more information.
What colour is the character? Yellow, Blue, Red?
What level (0-50, 50-120)?
What Race? Sura, Warrior, Shaman?
On which Map are you? Desert, Ice Land etc.

**Comment by kadirburlukkara** [comment]
What colour is the character? Red
What level (0-50, 50-120)? 50 120  stone lvl 90
What Race? Sura
On which Map are you? Red Forest

**Comment by SkidBit** [comment]
Okay, I'll do some tests.

**Comment by kadirburlukkara** [comment]
Thanks :+1:

**Comment by SkidBit** [comment]
Did you update your rubinum client with "RubinumLauncher.exe" ?

**Comment by kadirburlukkara** [comment]
Yes

**Comment by SkidBit** [comment]
Can you test on other characters/ in other places if it works?

**Comment by kadirburlukkara** [comment]
ok

**Comment by kadirburlukkara** [comment]
version 15 trying to hack the wall

**Comment by kadirburlukkara** [comment]
I guess the problem sura .
no problem
in the warrior

**Comment by kadirburlukkara** [comment]
ok 
problem solved

**Comment by SkidBit** [comment]
Nah, if sura is not working it's still a bug.
I will upload a new release soon. 
Please test it with the sura to make sure it runs.

**Comment by mrkadirbey0012** [comment]
No Not Sura
When I remove the belt, it corrects and after starting the boat, I wear the belt again and there is no problem

**Comment by kadirburlukkara** [comment]
I Will Write This In Turkish Translate and Read Please
Hata Surada Deil Kuşakta kuşagı Cikarıp istedigim ayarı yaptıgımda sorun olmuyor botu başlattıktan sona tekrar takıyorum

**Comment by SkidBit** [comment]
Hm... so your Belt is breaking the bot?
Turmalin Belt?

**Comment by kadirburlukkara** [comment]
no. Lord Sash

**Comment by SkidBit** [comment]
I released a new version, please use the 1.5.3 and check if the problem on your sura is still the same as before.

**Comment by kadirburlukkara** [comment]
Yes the problem is fixed but I will have a question. When you get out of the game and re-enter, the bot stops. Do I have a solution for this?

**Comment by SkidBit** [comment]
If you teleport or change characters etc. you should pause the bot with F1 and restart again with F1.
