### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by EmreK94** [SkidBit/Metin-2-Bot-Rubinum2-Pserver#6]
Hello, first of all thanks for sharing.

I don't experience any problems when I apply the .dll file you published v1.7.2. However, my game freeze and crashes when I download the source and try to create my own build. I never experienced such problem with the sources of previous versions. Could you please check? Thank you again.

**Comment by SkidBit** [comment]
Make sure to use Visual Studio 2019 with the v142 toolset and the newest win10 SDK.
Also build as release on x86.

There is not much more I can do to help you.

**Comment by EmreK94** [comment]
Thanks for the fast reply,

As i said, I never experienced such problem with the sources of previous versions

![sss](https://user-images.githubusercontent.com/77073104/103810232-f9f15e80-506b-11eb-8de0-c55694ce2be9.png)

**Comment by SkidBit** [comment]
Hm strange, the settings look fine.
The dll also compiles without errors?

**Comment by SkidBit** [comment]
Oh, in the settings window in the screenshot.
There are two drop down menus on the top. You need to set Release, also in VS set it to release. Maybe that helps

**Comment by SkidBit** [comment]
For me the debug build works too, I don't know why you have those problems. Are you injecting the correct Process? There are two Rubinum 2 processes, one is for the chromium and one is for the game. Use "Process Hacker" and sort the process list by "private bytes" and use the rubinum 2 process that has about 500 mb size.

**Comment by EmreK94** [comment]
I think my explanation about the issue was wrong, Just watch;

https://www.youtube.com/watch?v=ih3PRfvO4KU

**Comment by SkidBit** [comment]
Oh I see... that's weird. 
The bot reads your position correctly, so atleast some parts are working.
I will test some things, but I think it has to do with build configurations or something like that.

**Comment by SkidBit** [comment]
I made one commit after the release, maybe the problem is caused by that.

**Comment by SkidBit** [comment]
I made some tests with the new build, but for me everything is working so far.

**Comment by SkidBit** [comment]
@EmreK94 please try out release 1.8 and tell me if it also crashes. Thanks.

**Comment by EmreK94** [comment]
Yes its still crashing and your release (.dll) works properly =D btw why is the size of your .dll is different from mine.

https://youtu.be/te3moF3S4mE

**Comment by SkidBit** [comment]
The size is different, because you still build as DEBUG.
I told you two times already to build as RELEASE.
In the project settings on top you need to configure RELEASE. In the screenshot you showed me the configuration of DEBUG.
Also try this options under C/C++ -> Optimization: 
1. Maximum optimization (speed)
2. Standard
3. Yes
4. neither
5. no
6. no
7. yes
